// <auto-generated />
namespace TestProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class palce_image_db_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(palce_image_db_change));
        
        string IMigrationMetadata.Id
        {
            get { return "201601140622555_palce_image_db_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
